# db
services:
  db:
    image: postgres:latest
    container_name: db_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - mydb_data:/var/lib/postgresql/data
volumes:
  mydb_data:

